services:
  app:
    build:
      context: .
      dockerfile: cmd/api/infra/Dockerfile
    container_name: app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DSN: mysql:mysql@tcp(mysql:3306)/db?parseTime=true&loc=UTC
      RABBIT_URL: amqp://rabbit:rabbit@rabbitmq:5672/rabbit
      GUREN_KEY: 3b65ec7a99cd009b6e89ee0eed8cf660beb7c35bfd2add7e09e9232be02a2839
      WEBHOOK_SITE_URL: ""
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
      RABBITMQ_DEFAULT_VHOST: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s


volumes:
  mysql_data:
  rabbitmq_data:
